Workout-Shop/Models/Entites/Plan.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Workout_Shop.Data.Base.Interface;
using Workout_Shop.Data.Enums;
using Workout_Shop.Models.Relationships;

namespace Workout_Shop.Models.Entites
{
    public class Plan:IEntityBase
    {
        [Key]
        public int Id { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public double Price { get; set; }

        public int count { get; set; }

        public string ImageURL { get; set; }

        public DateTime StartDate { get; set; }

        public DateTime EndDate { get; set; }

        public WorkoutCategory WorkoutCategory { get; set; }



        //Relationship

        public List<Instructor_Plan> Instructor_Plan { get; set; }


        //Gym
        public int GymId { get; set; }
        [ForeignKey("GymId")]
        public Gyms Gyms { get; set; }

        //Main Instructor
        public int MainInstructorId { get; set; }
        [ForeignKey("MainInstructorId")]
        public MainInstructor MainInstructor { get; set; }

    }
}

Workout-Shop/Models/ViewModel/PlanViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Workout_Shop.Data.Base.Interface;
using Workout_Shop.Data.Enums;
using Workout_Shop.Models.Relationships;

namespace Workout_Shop.Models
{
    public class PlanViewModel
    {

        [Required(ErrorMessage = "Name is required") ]
        [Display(Description = "Plan Name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Descrption is required")]
        [Display(Description = "Plan Description")]
        public string Description { get; set; }

        [Required(ErrorMessage = "Price is required")]
        [Display(Description = "Plan Price")]
        public double Price { get; set; }

        public string ImageURL { get; set; }

        public DateTime StartDate { get; set; }

        public DateTime EndDate { get; set; }

        public WorkoutCategory WorkoutCategory { get; set; }

        //Relationship

        public List<int> InstructorId { get; set; }


        //Gym
        public int GymId { get; set; }
        

        //Main Instructor
        public int MainInstructorId { get; set; }
        public int Id { get; set; }
    }
}

Workout-Shop/Controllers/InstructorsController.cs
using Microsoft.AspNetCore.Mvc;
using Workout_Shop.Data;
using Workout_Shop.Data.Service.IService;
using Workout_Shop.Models.Entites;

namespace Workout_Shop.Controllers
{
    public class InstructorsController : Controller
    {
        private readonly IInstructorService _instructorService;

        public InstructorsController(IInstructorService instructorService)
        {
           _instructorService = instructorService;
        }
        
        public async Task<IActionResult> Index()
        {
            var data = await  _instructorService.GetAllAsync();
            return View(data);
        }



        public async Task<IActionResult> Create()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Create([Bind("FullName,ProfilePicture,Biography")]Instructor instructor)
        {
            if(ModelState.IsValid)
            {
                return View(instructor);
            }

           await _instructorService.AddAsync(instructor);

            return RedirectToAction(nameof(Index));
        }


        
        public async Task<IActionResult> Details (int id)
        {
            var InstructorDetails =await _instructorService.GetByIdAsync(id);

            if(InstructorDetails == null) {

                return View("NotFound");
            }

             return View(InstructorDetails);


        }

        //Get : Actors/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var instructorDetails = await _instructorService.GetByIdAsync(id);

            if (instructorDetails == null)
            {

                return View("NotFound");
            }

            return View(instructorDetails);
        }


        [HttpPost]
        public async Task<IActionResult> Edit(int id, Instructor instructor)
        {
            if (ModelState.IsValid)
            {
                return View(instructor);
            }

            await _instructorService.UpdateAsync(id, instructor);

            return RedirectToAction(nameof(Index));
        }


        //Get : Actors/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var instructorDetails = await _instructorService.GetByIdAsync(id);

            if (instructorDetails == null)
            {

                return View("NotFound");
            }

            return View(instructorDetails);
        }


        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var instructorDetails = await _instructorService.GetByIdAsync(id);
            if (instructorDetails == null)
            {

                return View("NotFound");
            }

            await _instructorService.DeleteAsync(id);

            return RedirectToAction(nameof(Index));
        }

    }
}

Workout-Shop/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Workout_Shop.Data.Cart;
using Workout_Shop.Data.Service;
using Workout_Shop.Data.Service.IService;
using Workout_Shop.Models.ViewModel;

namespace Workout_Shop.Controllers
{
    public class OrdersController : Controller
    {

        private readonly IPlansService _plansService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrderService _ordersService;

        public OrdersController(IPlansService plansService, ShoppingCart shoppingCart, IOrderService ordersService)
        {
            _plansService = plansService;
            _shoppingCart = shoppingCart;
            _ordersService = ordersService;
        }

        public async Task<IActionResult> Index()
        {
            string userId = "";
            string userRole = "";

            var orders = await _ordersService.GetOrdersByUserIdAndRoleAsync(userId, userRole);
            return View(orders);
        }

        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var response = new ShoppingCartViewModel()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(response);
        }

        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _plansService.GetPlanByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _plansService.GetPlanByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            var planIds = items.Select(n => n.Plan.Id).ToList();


            string userId = "";
            string userEmailAddress = "";

            foreach (var planId in planIds)
            {
            
                await _plansService.AddCountAsync(planId);
            }

            await _ordersService.StoreOrderAsync(items, userId, userEmailAddress);
            await _shoppingCart.ClearShoppingCartAsync();

            return View("OrderCompleted");
        }
    }
}

Workout-Shop/Controllers/PlansController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Reflection.Metadata.Ecma335;
using Workout_Shop.Data;
using Workout_Shop.Data.Service.IService;
using Workout_Shop.Models;
using Workout_Shop.Models.Entites;
using Workout_Shop.Models.Relationships;
using Workout_Shop.Models.ViewModel;


namespace Workout_Shop.Controllers
{
    public class PlansController : Controller
    {
        private readonly IPlansService _service;

        public PlansController(IPlansService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAllAsync(n => n.Gyms);
            return View(data);
        }

        public async Task<IActionResult> Filter(string searchString)
        {
            var data = await _service.GetAllAsync(n => n.Gyms);

            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredResult = data.Where(p => p.Name.Contains(searchString) || p.Description.Contains(searchString)).ToList();
                return View("Index",filteredResult);
            }
            return View("Index", data);
        }


        public async Task<IActionResult> Details(int id)
        {
            var planDetails = await _service.GetPlanByIdAsync(id);
            return View(planDetails);
        }

        public async Task<IActionResult> Create()
        {
            var planDropdownData = await _service.GetNewPlanDropdownValues();

            ViewBag.GymsId = new SelectList(planDropdownData.Gyms, "Id", "Name");
            ViewBag.MainInstructorId = new SelectList(planDropdownData.MainInstructors, "Id", "FullName");
            ViewBag.InstructorId = new SelectList(planDropdownData.Instructors, "Id", "FullName");

            return View();

        }

        [HttpPost]
        public async Task<IActionResult> Create(PlanViewModel plan)
        {
            if(!ModelState.IsValid)
            {
                var planDropdownData = await _service.GetNewPlanDropdownValues();

                ViewBag.GymsId = new SelectList(planDropdownData.Gyms, "Id", "Name");
                ViewBag.MainInstructorId = new SelectList(planDropdownData.MainInstructors, "Id", "FullName");
                ViewBag.InstructorId = new SelectList(planDropdownData.Instructors, "Id", "FullName");

                return View(plan);
            }

            await _service.AddNewPlanAsync(plan);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(int id)
        {
            var planDetails = await _service.GetPlanByIdAsync(id);

            if(planDetails == null)  return View ("Not Found");

            var response = new PlanViewModel()
            {
                Id = planDetails.Id,
                Name = planDetails.Name,
                Price = planDetails.Price,
                Description = planDetails.Description,
                ImageURL = planDetails.ImageURL,
                StartDate = planDetails.StartDate,
                EndDate = planDetails.EndDate,
                WorkoutCategory = planDetails.WorkoutCategory,
                GymId = planDetails.GymId,
                MainInstructorId = planDetails.MainInstructorId,
                InstructorId = planDetails.Instructor_Plan.Select(n =>n.InstructorId).ToList(),
            };

            var planDropdownData = await _service.GetNewPlanDropdownValues();

            ViewBag.GymsId = new SelectList(planDropdownData.Gyms, "Id", "Name");
            ViewBag.MainInstructorId = new SelectList(planDropdownData.MainInstructors, "Id", "FullName");
            ViewBag.InstructorId = new SelectList(planDropdownData.Instructors, "Id", "FullName");

            return View(response);

        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, PlanViewModel plan)
        {
            if (id != plan.Id) return View("NotFound");

            if (!ModelState.IsValid)
            {
                var planDropdownData = await _service.GetNewPlanDropdownValues();

                ViewBag.GymsId = new SelectList(planDropdownData.Gyms, "Id", "Name");
                ViewBag.MainInstructorId = new SelectList(planDropdownData.MainInstructors, "Id", "FullName");
                ViewBag.InstructorId = new SelectList(planDropdownData.Instructors, "Id", "FullName");

                return View(plan);
            }

            await _service.UpdateNewPlanAsync(plan);
            return RedirectToAction(nameof(Index));
        }

    }
}

Workout-Shop/Views/Plans/Details.cshtml
@using Workout_Shop.Models.Entites
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Plan

@{
    ViewData["Title"] = " Plan Details";
}

<div class="info">
    <div class="left-side">
        <div class="image-container">
            <img src="@Model.ImageURL" width="100%" alt="@Model.Name"></img>
        </div>

        <div class="plan-info">
            <div class="title-name"><h1>@Model.Name</h1></div>
        </div>

        <div class="add-to-cart">
            <a class="btn float-right" asp-controller="Orders" asp-action="AddItemToShoppingCart" asp-route-id="@Model.Id"><i class="bi bi-eye-fill"></i>Add to Cart(Price @Model.Price.ToString("c"))</a>
            <a class="btn float-right" asp-action="Index">
                Back To List
            </a>
        </div>
        
    </div>
    <div class="right-side">
        <div class="text-container"><p>Description: @Model.Description</p></div>
        <div class="plan-info-2">
            <div class="gym-name"><p>@Model.Gyms.Name</p></div>
            <div class="price-tag"><p>@Model.WorkoutCategory</p></div>
        </div>

        <div class="instructor-box">
        @foreach (var instructor in Model.Instructor_Plan)
        {
            <div class="instructor-container">
                <img class="border-info rounded-circle" src="@instructor.Instructor.ProfilePicture" style="max-width: 150px" />
                <br />
                <a asp-controller="Instructors" asp-action="Details" asp-route-id="@instructor.InstructorId">@instructor.Instructor.FullName</a>
            </div>
        }
        </div>
    </div>
</div>

Workout-Shop/Views/Plans/Edit.cshtml
@model PlanViewModel;
@using Workout_Shop.Data.Enums

@{
    ViewData["Title"] = "Create a new movie";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>Update a Plan</h4>
        </p>

        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="StartDate" class="control-label"></label>
                                <input asp-for="StartDate" type="date" class="form-control" />
                                <span asp-validation-for="StartDate" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="EndDate" class="control-label"></label>
                                <input asp-for="EndDate" type="date" class="form-control" />
                                <span asp-validation-for="EndDate" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Price" class="control-label"></label>
                                <input asp-for="Price" type="number" class="form-control" />
                                <span asp-validation-for="Price" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ImageURL" class="control-label"></label>
                                <input asp-for="ImageURL" class="form-control" />
                                <span asp-validation-for="ImageURL" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="GymId" class="control-label"></label>
                                <select asp-for="GymId" class="form-control" asp-items="ViewBag.GymsId"></select>
                                <span asp-validation-for="GymId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="WorkoutCategory" class="control-label"></label>
                                <select asp-for="WorkoutCategory" class="form-control" asp-items="Html.GetEnumSelectList<WorkoutCategory>()"></select>
                                <span asp-validation-for="WorkoutCategory" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="MainInstructorId" class="control-label"></label>
                                <select asp-for="MainInstructorId" class="form-control" asp-items="ViewBag.MainInstructorId"></select>
                                <span asp-validation-for="MainInstructorId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="InstructorId" class="control-label"></label>
                                <select asp-for="InstructorId" class="form-control" asp-items="ViewBag.InstructorId"></select>
                                <span asp-validation-for="InstructorId" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <textarea asp-for="Description" class="form-control"></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-4 offset-4 text-center">
                        <img width="100%" id="ImageUrlPreview" />
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Update" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show all</a>
                    </div>

                </form>

            </div>
        </div>

    </div>
</div>

@section Scripts {
    <script>

        $(document).ready(function () {
            var output = document.getElementById("ImageUrlPreview");
            output.src = $("#ImageURL").val();
        })

        $("#ImageURL").on("change", function () {
            var output = document.getElementById("ImageUrlPreview");
            output.src = $(this).val();
        })
    </script>
}

Workout-Shop/Views/Plans/Index.cshtml
@using Workout_Shop.Models.Entites
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model IEnumerable<Plan>

@{
    ViewData["Title"] = "List of Plans";
}



<div class="plan-container">
    <div class="box">
        <form  asp-controller="Home" asp-action="Index">
            <input type="text" class="input" name="txt" onmouseout="this.value = ''; this.blur();">
            @* <button class="btn-search"><i class="bi bi-search"></i></button> *@
        </form>
        <i class="bi bi-search"></i>
    </div>

    <div class="plan-box">
    @foreach(var item in Model)
    {
        
        <div class="col-md-4 col-xs-6 border-primary mb-3">
            <div class="card mb-3" style="max-width:540px;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text">
                            <p class="card-text">
                                <h5 class="card-title">
                                    @item.Name
                                    <a class="text-white float-right" asp-action="Edit" asp-route-id="@item.Id"><i class="bg-info bi-pencil-square"></i></a>
                                </h5>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img src="@item.ImageURL" width="100%" alt="@item.Name"></img>
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            
                            <p class="card-text"><b>Gym</b> @item.Gyms.Name</p> 
                            <p class="card-text"><b>Category</b> @item.WorkoutCategory</p>
                            <p class="card-text"><b>Downloads</b> @item.count</p>
                            <p class="card-text"><b>Start Date</b> @item.StartDate.ToString("dd/MMM/yyy")</p>
                            <p class="card-text"><b>End Date</b> @item.EndDate.ToString("dd/MMM/yyy")</p>
                            <p class="card-text"><b>Status</b> 
                                @if (DateTime.Now >= item.StartDate && DateTime.Now <= item.EndDate)
                                {
                                    <span class="badge bg-available">Available</span>
                                }
                                else if (DateTime.Now >= item.StartDate && DateTime.Now <= item.EndDate.AddDays(-15))
                                {

                                    <span class="badge bg-ending-soon">Ending Soon</span>
                                }
                                else{
                                    <span class="badge bg-completed">Completed</span>
                                    
                                    }
                                </p>
                        </div>
                    </div>
                </div>
                <div class="col-md-13">
                    <div class="card-footer">
                        <p class="card-text">
                            <a class="btn float-right" asp-action="Details" asp-route-id="@item.Id"><i class="bi bi-eye-fill"></i>Show Details</a>
                            <a class="btn float-right" asp-controller="Orders" asp-action="AddItemToShoppingCart" asp-route-id="@item.Id">Add to Cart(Price @item.Price.ToString("c"))</a>
                        </p>

                    </div>
                </div>
            </div>
        </div>
        

    }
    </div>
</div>



@await Html.PartialAsync("_CreateItem", "Plans")