Workout-Shop/Controllers/GymsController.cs
using Microsoft.AspNetCore.Mvc;
using Workout_Shop.Data;
using Workout_Shop.Data.Service;
using Workout_Shop.Data.Service.IService;
using Workout_Shop.Models.Entites;

namespace Workout_Shop.Controllers
{
    public class GymsController : Controller
    {
        private readonly IGymsService _service;

        public GymsController(IGymsService service)
        {
            _service = service;
        }


        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAllAsync();
            return View(data);
        }


        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Logo", "Name", "Description")] Gyms gyms)
        {
            if (ModelState.IsValid) { return View(gyms); }
            await _service.AddAsync(gyms);
            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> Details(int id)
        {
            var data = await _service.GetByIdAsync(id);
            if (data == null)  return View("NotFound");
                return View(data);
        }


        public async Task<IActionResult> Edit(int id)
        {
            var gymDetails = await _service.GetByIdAsync(id);

            if (gymDetails == null)
            {

                return View("NotFound");
            }
            return View(gymDetails);
        }


        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id, Logo, Name, Description")] Gyms gyms)
        {
            if (ModelState.IsValid)
            {
                return View(gyms);
            }
                await _service.UpdateAsync(id, gyms);
            return RedirectToAction(nameof(Index)); 
        }


        public async Task<IActionResult> Delete(int id)
        {
            var gymsDetails = await _service.GetByIdAsync(id);

            if (gymsDetails == null)
            {

                return View("NotFound");
            }

            return View(gymsDetails);
        }


        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var gymsDetails = await _service.GetByIdAsync(id);
            if (gymsDetails == null)
            {

                return View("NotFound");
            }

            await _service.DeleteAsync(id);

            return RedirectToAction(nameof(Index));
        }

    }
}

Workout-Shop/Controllers/InstructorsController.cs
using Microsoft.AspNetCore.Mvc;
using Workout_Shop.Data;
using Workout_Shop.Data.Service.IService;
using Workout_Shop.Models.Entites;

namespace Workout_Shop.Controllers
{
    public class InstructorsController : Controller
    {
        private readonly IInstructorService _instructorService;

        public InstructorsController(IInstructorService instructorService)
        {
           _instructorService = instructorService;
        }
        
        public async Task<IActionResult> Index()
        {
            var data = await  _instructorService.GetAllAsync();
            return View(data);
        }



        public async Task<IActionResult> Create()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Create([Bind("FullName,ProfilePicture,Biography")]Instructor instructor)
        {
            if(ModelState.IsValid)
            {
                return View(instructor);
            }

           await _instructorService.AddAsync(instructor);

            return RedirectToAction(nameof(Index));
        }


        
        public async Task<IActionResult> Details (int id)
        {
            var InstructorDetails =await _instructorService.GetByIdAsync(id);

            if(InstructorDetails == null) {

                return View("NotFound");
            }

             return View(InstructorDetails);


        }

        //Get : Actors/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var instructorDetails = await _instructorService.GetByIdAsync(id);

            if (instructorDetails == null)
            {

                return View("NotFound");
            }

            return View(instructorDetails);
        }


        [HttpPost]
        public async Task<IActionResult> Edit(int id, Instructor instructor)
        {
            if (ModelState.IsValid)
            {
                return View(instructor);
            }

            await _instructorService.UpdateAsync(id, instructor);

            return RedirectToAction(nameof(Index));
        }


        //Get : Actors/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var instructorDetails = await _instructorService.GetByIdAsync(id);

            if (instructorDetails == null)
            {

                return View("NotFound");
            }

            return View(instructorDetails);
        }


        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var instructorDetails = await _instructorService.GetByIdAsync(id);
            if (instructorDetails == null)
            {

                return View("NotFound");
            }

            await _instructorService.DeleteAsync(id);

            return RedirectToAction(nameof(Index));
        }

    }
}

Workout-Shop/Controllers/PlansController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Reflection.Metadata.Ecma335;
using Workout_Shop.Data;
using Workout_Shop.Data.Service.IService;
using Workout_Shop.Models;
using Workout_Shop.Models.Entites;
using Workout_Shop.Models.Relationships;
using Workout_Shop.Models.ViewModel;


namespace Workout_Shop.Controllers
{
    public class PlansController : Controller
    {
        private readonly IPlansService _service;

        public PlansController(IPlansService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAllAsync(n => n.Gyms);
            return View(data);
        }

        public async Task<IActionResult> Filter(string searchString)
        {
            var data = await _service.GetAllAsync(n => n.Gyms);

            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredResult = data.Where(p => p.Name.Contains(searchString) || p.Description.Contains(searchString)).ToList();
                return View("Index",filteredResult);
            }
            return View("Index", data);
        }


        public async Task<IActionResult> Details(int id)
        {
            var planDetails = await _service.GetPlanByIdAsync(id);
            return View(planDetails);
        }

        public async Task<IActionResult> Create()
        {
            var planDropdownData = await _service.GetNewPlanDropdownValues();

            ViewBag.GymsId = new SelectList(planDropdownData.Gyms, "Id", "Name");
            ViewBag.MainInstructorId = new SelectList(planDropdownData.MainInstructors, "Id", "FullName");
            ViewBag.InstructorId = new SelectList(planDropdownData.Instructors, "Id", "FullName");

            return View();

        }

        [HttpPost]
        public async Task<IActionResult> Create(PlanViewModel plan)
        {
            if(!ModelState.IsValid)
            {
                var planDropdownData = await _service.GetNewPlanDropdownValues();

                ViewBag.GymsId = new SelectList(planDropdownData.Gyms, "Id", "Name");
                ViewBag.MainInstructorId = new SelectList(planDropdownData.MainInstructors, "Id", "FullName");
                ViewBag.InstructorId = new SelectList(planDropdownData.Instructors, "Id", "FullName");

                return View(plan);
            }

            await _service.AddNewPlanAsync(plan);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(int id)
        {
            var planDetails = await _service.GetPlanByIdAsync(id);

            if(planDetails == null)  return View ("Not Found");

            var response = new PlanViewModel()
            {
                Id = planDetails.Id,
                Name = planDetails.Name,
                Price = planDetails.Price,
                Description = planDetails.Description,
                ImageURL = planDetails.ImageURL,
                StartDate = planDetails.StartDate,
                EndDate = planDetails.EndDate,
                WorkoutCategory = planDetails.WorkoutCategory,
                GymId = planDetails.GymId,
                MainInstructorId = planDetails.MainInstructorId,
                InstructorId = planDetails.Instructor_Plan.Select(n =>n.InstructorId).ToList(),
            };

            var planDropdownData = await _service.GetNewPlanDropdownValues();

            ViewBag.GymsId = new SelectList(planDropdownData.Gyms, "Id", "Name");
            ViewBag.MainInstructorId = new SelectList(planDropdownData.MainInstructors, "Id", "FullName");
            ViewBag.InstructorId = new SelectList(planDropdownData.Instructors, "Id", "FullName");

            return View(response);

        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, PlanViewModel plan)
        {
            if (id != plan.Id) return View("NotFound");

            if (!ModelState.IsValid)
            {
                var planDropdownData = await _service.GetNewPlanDropdownValues();

                ViewBag.GymsId = new SelectList(planDropdownData.Gyms, "Id", "Name");
                ViewBag.MainInstructorId = new SelectList(planDropdownData.MainInstructors, "Id", "FullName");
                ViewBag.InstructorId = new SelectList(planDropdownData.Instructors, "Id", "FullName");

                return View(plan);
            }

            await _service.UpdateNewPlanAsync(plan);
            return RedirectToAction(nameof(Index));
        }

    }
}

Workout-Shop/Controllers/WorkoutController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Workout_Shop.Data;

namespace Workout_Shop.Controllers
{
    public class WorkoutController : Controller
    {
        private readonly ApplicationDBContext _dbContext;

        public WorkoutController(ApplicationDBContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IActionResult Index()
        {
            var allWorkouts = _dbContext.Workouts.Include(n => n.Gyms).ToList();
            return View(allWorkouts);
        }
    }
}

Workout-Shop/Views/Shared/NotFound.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

﻿<div class="row">
    <div class="col-md-6 offset-3">
        <h1 class="text-info">You've reached the end of the internet</h1>
        <hr />
        <a class="btn btn-outline-success" asp-controller="Workout" asp-action="Index">Home Page</a>
    </div>
</div>

Workout-Shop/Views/Shared/_CreateItem.cshtml
@model String;

<div style="position : fixed; right: 25px; bottom: 25px" class="text-white">
    <a asp-controller="@Model" asp-action="Create" class="btn btn-success"><i class="bi bi-plus-circle"></i> Add New </a>  @* The as ASP action returns views from the controller*@
</div>

Workout-Shop/Views/Shared/_Homepage.cshtml
@model String;

<div style="position : fixed; right: 25px; top: 25px" class="text-white">
    <a asp-controller="Home" asp-action="Index" class="btn btn-success"><i class="bi bi-home"></i> Homepage </a>  
</div>

Workout-Shop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Workout_Shop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Workout_Shop.styles.css" asp-append-version="true" /> 
    <link rel="stylesheet" href="~/css/Plans.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">Workout With Me</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="dropdown-item" asp-area="" asp-controller="Plans" asp-action="Index"><i class="bi bi-camera-reels"></i> Workout</a>
                    </li>
                    <li class="nav-item">
                        <a class="dropdown-item" asp-controller="Gyms" asp-action="Index"> Gyms </a>

                    </li>
                    <li class="nav-item">
                        <a class="dropdown-item" asp-controller="MainInstructor" asp-action="Index"><i class="bi bi-headset"></i> Main Instructors</a>

                    </li>
                    <li class="nav-item">
                        <a class="dropdown-item" asp-controller="Instructors" asp-action="Index"><i class="bi bi-person-square"></i> Instructors </a>

                    </li>

                </ul>


            </div>
        </div>
       
        <ul class="navbar-nav">
            @await Component.InvokeAsync("ShoppingCartSummary")
        </ul>
    </nav>
    

    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <!-- Footer content here -->
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>